### PR TITLE
Remove mapping of file_title and file_author

### LINKED ISSUE #226: Change default mapping for file and author properties from characterization.
The downstream uses have FileSets with author and title properties.  The ch12n properties should be file_author and file_title so as not to conflict with the existing author and title of the FileSet.

The current implementation where the OM term is remapped from file_title to title was short sighted.  It did not assume the case where a FileSet would already have those methods.  As such, the ch12n values will overwrite the FileSet values.

Simply removing the mapping in the Document module will effect this change.
```
parser_mapping.merge!(file_title: :title,
                            file_author: :author)
```

### PR DESCRIPTION
**Pull request by grosscol**
Fixes #226
Remove custom mapping of file_title and file_author.
This will avoid over writing existing title and author values.

### CODE REVIEW

**Comment by jcoyne** [comment]
This is a feature that you are removing. In Sufia you would get to the metadata page and it would have these values entered from the ch18n

**Comment by grosscol** [comment]
I'm actually reverting to the prior behavior of file_author and file_title instead of author and title.  In curation concerns, the FileSet has both a file_author and author method.  The file_author is from characterization and author is from the descriptive metadata.

If the method already exists for title and author, characterization will happily use these when assigning values.  So if the FileSet had a different title than what ch12n determined from the bitstream, it would get overwritten when ch12n runs.

I am expecting the situation where someone uploads a file which is 'kevin_dataset-new(2)-final.xlsx' but specifies the title as 'final dataset' in the upload form.  I would not like 'final dataset' to get overwritten with 'kevin_dataset-new(2)-final.xlsx' or whatever garbage the office application filled in for the title of it's metadata.

**Comment by mjgiarlo** [comment]
Travis is :unamused:

**Comment by mjgiarlo** [comment]
@jcoyne Are you :ok: with what @grosscol described?

**Comment by mjgiarlo** [comment]
:+1: otherwise

**Comment by jcoyne** [comment]
@mjgiarlo if you're okay, sure.

**Pull request merged**
