### PR TITLE
Don't require ActiveFedora::Aggregation anymore

### PR DESCRIPTION
**Pull request by awead**
@barmintor

### CODE REVIEW

**Comment by jcoyne** [comment]
Shouldn't you add a dependency on AF >= 9.11

**Comment by jcoyne** [comment]
@awead or requiring hydra-pcdm >= 0.6  will accomplish that transitively

**Comment by awead** [comment]
@jcoyne yes, that makes sense. And we're okay with breaking backwards compatibility? Although there isn't any expectation of that, is there.

**Comment by awead** [comment]
@jcoyne updated.

**Pull request merged**
