### PR TITLE
Add file more kargs

### PR DESCRIPTION
**Pull request by flyingzumwalt**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Failed specs but :+1: to the code otherwise.

**Comment by flyingzumwalt** [comment]
Note: Github's display of the builds is misleading.  The correct build to watch is here: https://travis-ci.org/projecthydra-labs/hydra-works/builds/69916610

**Comment by mjgiarlo** [comment]
Happy to merge this once it's all :green_apple:

**Comment by flyingzumwalt** [comment]
Rebased against master. Travis failed on something that was fixed in PR #137.  Now the build to watch is   https://travis-ci.org/projecthydra-labs/hydra-works/builds/69919821

**Comment by mjgiarlo** [comment]
@flyingzumwalt OK. It looks like GitHub picked up the right builds this time. Waiting on those to spin up and finish.

**Comment by flyingzumwalt** [comment]
:green_apple:

**Comment by mjgiarlo** [comment]
:+1:  (I have a follow-up question I'll ask on IRC.)

**Pull request merged**
