### PR TITLE
New services for adding and getting collections, generic works, and generic files.  De-dup tests.

### PR DESCRIPTION
**Pull request by elrayle**

### CODE REVIEW

**Comment by awead** [comment]
@elrayle It would be helpful if the tests marked with `xit` used skip instead:
```
it "should do somthing" do
  skip "skipping this test because issue #XX needs to be addressed"
end
```
The skip messages are displayed when the test suite is run so we can why we're not running it. Please make sure that any skipped tests have a corresponding issue. I think this is the case already, but we need to indicate which test go with which issues.

Other than, :clap: great work!!!!

**Comment by elrayle** [comment]
@awead I updated the PR to use skip instead of xit.  That was a good suggestion.  I like having the issue number print out when the tests run.  Similarly, when I have a TODO in the code, I include the issue number in the TODO statement.

**Comment by elrayle** [comment]
Once this is merged, I will follow it with a PR related to remove services.

**Comment by elrayle** [comment]
Fixes https://github.com/projecthydra-labs/hydra-works/pull/104

**Pull request merged**
