### PR TITLE
Remove filter associations

### PR DESCRIPTION
**Pull request by terrellt**
Companion to https://github.com/projecthydra-labs/hydra-pcdm/pull/186.

### CODE REVIEW

**Comment by terrellt** [comment]
Ready for merge. @jcoyne @mjgiarlo @elrayle ?

**Comment by jcoyne** [comment]
:+1: do you want to squash these commits?

**Comment by terrellt** [comment]
Squashed

**Comment by mjgiarlo** [comment]
Travis is :unamused: and coverage dropped 8%.

**Comment by terrellt** [comment]
What?! It was fine pre squash

**Comment by mjgiarlo** [comment]
I didn't do it!

**Comment by terrellt** [comment]
@mjgiarlo Take another look?

**Comment by mjgiarlo** [comment]
:+1:

**Pull request merged**
