### PR TITLE
Deleted contains= from spec and lib

### PR DESCRIPTION
**Pull request by njaffer**
Deleted unused method def 'contains=' from spec and lib

### CODE REVIEW

**Comment by mjgiarlo** [comment]
I suspect that "config" file may have crept into this commit by mistake.  Remove and push changes?  Otherwise :+1:

**Comment by njaffer** [comment]
removed config and pushed the changes

**Comment by mjgiarlo** [comment]
@njaffer Great!  Can you squash your two commits together?  More on that here:

http://ndlib.github.io/practices/one-commit-per-pull-request/

**Comment by njaffer** [comment]
Ok done.. @mjgiarlo , the article you share is very helpful - Thanks

**Comment by mjgiarlo** [comment]
Thanks, @njaffer!

**Pull request merged**
