### PR TITLE
Migrating virus check functionality from CurationConcerns

### PR DESCRIPTION
**Pull request by escowles**
Addresses #94 (part 1 of 2)

### CODE REVIEW

**Comment by jcoyne** [comment]
This seems like business logic more than modeling. As such does it belong in hydra-works?  I'm not against it being here, I'm just making sure we're considering it thoughtfully.

**Comment by escowles** [comment]
@jcoyne I think the reasoning for moving this down to hydra-works is to have all of the core functionality here (generating derivatives, creating versions, checking for viruses, etc.) so you don't have to use curation_concerns to get that functionality.

**Comment by jcoyne** [comment]
Yes, I now see that derivatives are here, so it probably belongs with that.

**Comment by jcoyne** [comment]
Should there be something added to the Readme saying "Add clamav to your gemfile to enable virus checking"

**Comment by jpstroop** [comment]
Close projecthydra-labs/curation_concerns#37 and move [this part of CurationConcern's README](https://github.com/projecthydra-labs/curation_concerns#virus-detection) here when this goes through.

**Comment by mjgiarlo** [comment]
@escowles Do you want to include the README change that @jpstroop suggests in this PR, or attach that to part 2?

:+1:

**Comment by escowles** [comment]
@mjgiarlo I'll add the README update to this PR -- and then part 2 will be updating curation_concerns to use this virus check instead of its own

**Comment by jpstroop** [comment]
Actually, it's even more than that; [virus check is also in CurationConcerns](https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/models/concerns/curation_concerns/generic_file/virus_check.rb) :cry: , so that should be removed. I'll update projecthydra-labs/curation_concerns#37

**Comment by jpstroop** [comment]
Doh!

**Comment by mjgiarlo** [comment]
@escowles OK. I'll merge this PR as soon as you tweak the README. (I won't bother waiting on travis for a README change -- we already know the suite passes.) Ping me when that's ready.

**Pull request merged**
