### PR TITLE
Improves handling of Contained Files and moves some File functionality to hydra-pcdm

### PR DESCRIPTION
**Pull request by flyingzumwalt**

### CODE REVIEW

**Comment by flyingzumwalt** [comment]
If there are no objections to these changes, I'll squash the commits.

**Comment by awead** [comment]
:+1:

**Comment by flyingzumwalt** [comment]
@awead I spoke with @jcoyne and he said to go ahead with these merges -- he's not available to review this week.  Could you merge projecthydra-labs/hydra-pcdm#112 and this?

**Comment by jcoyne** [comment]
Okay, projecthydra-labs/hydra-pcdm#112 is merged. These commits are ready to squash.

**Comment by jcoyne** [comment]
Actually, it think it's more readable if they are not squashed.

**Pull request merged**
