### PR TITLE
Bump gemspec to a released version of hydra-derivatives

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Build failed, presumably because hydra-derivatives 3.0 was not yet fully registered at rubygems.org. I :recycle: the builds.

**Comment by mjgiarlo** [comment]
Still failing. Not sure why it's not finding the 3.0 version of hydra-derivatives.

**Comment by jcoyne** [comment]
Probably gemfile.extra. I forgot about that

**Comment by mjgiarlo** [comment]
:ok:, ping me when travis is happy again and I'll gladly merge.

**Comment by jcoyne** [comment]
@mjgiarlo it's happy

**Pull request merged**
